<?php

return [

    'name' => env('APP_NAME', 'TornOps'),
    'env' => env('APP_ENV', 'production'),
    'debug' => (bool) env('APP_DEBUG', false),
    'url' => env('APP_URL', 'http://localhost'),
    'asset_url' => env('ASSET_URL'),
    'timezone' => 'UTC',
    'locale' => 'en',
    'fallback_locale' => 'en',
    'faker_locale' => 'en_US',
    'key' => env('APP_KEY'),
    'cipher' => 'AES-256-CBC',
    'master_key' => env('MASTER_KEY', ''),
    'tornops_image' => env('TORN_OPS_IMAGE', 'ghcr.io/bafplus/tornops/tornops:latest'),
    'data_volume_path' => env('DATA_VOLUME_PATH', '/data/tornops'),
    'tornops_url' => env('TORN_OPS_URL', 'https://tornops.net'),
    'tornops_domain' => env('TORN_OPS_DOMAIN', 'tornops.net'),
    'tornops_base_path' => env('TORN_OPS_BASE_PATH', '/home/server/tornops-instances'),
    'tornops_port_start' => env('TORN_OPS_PORT_START', 8082),
    'cloudflare_email' => env('CLOUDFLARE_EMAIL', 'bart.cockheyt@gmail.com'),
    'cloudflare_key' => env('CLOUDFLARE_KEY', 'd888ebd7a3d4da09d50f35b1c6dea49d92f96'),
    'cloudflare_account_id' => env('CLOUDFLARE_ACCOUNT_ID', '7ea602d1cd797bf3cb34885c9d240114'),
    'cloudflare_tunnel_id' => env('CLOUDFLARE_TUNNEL_ID', 'b5999d7d-67f0-461f-9513-7b8dcb15766d'),
    'cloudflare_zone_id' => env('CLOUDFLARE_ZONE_ID', '677fb6d5519e5c230f1de82aba4e8cb2'),
    'maintenance' => [
        'driver' => 'file',
    ],

    'providers' => [
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        App\Providers\AppServiceProvider::class,
        App\Providers\DiscordServiceProvider::class,
    ],

    'aliases' => Illuminate\Support\Facades\Facade::defaultAliases()->merge([
    ])->toArray(),

];
